services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:17
    container_name: credito_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credito_pj
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credito_pj"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio:
    image: quay.io/minio/minio:latest
    container_name: credito_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9000/minio/health/ready >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ml_service:
    build: ./ml_service
    pull_policy: never
    image: plataforma-credito-pj/ml_service:latest
    container_name: credito_ml_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    volumes:
      - ./ml_service:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  core-api:
    build: ./core-api
    pull_policy: never
    image: plataforma-credito-pj/core-api:latest
    container_name: credito_core_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      ml_service:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/credito_pj
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    pull_policy: never
    image: plataforma-credito-pj/etl:latest
    container_name: credito_etl
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/credito_pj
    working_dir: /app
    command: ["python", "run_all.py"]
    volumes:
      - ./etl:/app
      - "./Challenge FIAP - Bases.xlsx:/app/Challenge FIAP - Bases.xlsx"
    restart: "no"

  trainer:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    pull_policy: never
    image: plataforma-credito-pj/trainer:latest
    container_name: credito_trainer
    working_dir: /app
    command: ["python", "train_models.py"]
    volumes:
      - ./ml_service:/app
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      etl:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/credito_pj
    restart: "no"

  front-end:
    build: ./front-end
    pull_policy: never
    image: plataforma-credito-pj/front-end:latest
    container_name: credito_front_end
    ports:
      - "4200:80"
    depends_on:
      core-api:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  pgdata:
  minio_data:
