# docker-compose.yml (mínimo para testes)
version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: credito_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credito_pj
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

